services:
  weatherdb:
    image: postgres:latest
    container_name: weatherdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#    networks:
#      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    environment:
      WEATHER_DB_URL: jdbc:postgresql://localhost:5432/postgres
      WEATHER_DB_USERNAME: postgres
      WEATHER_DB_PASSWORD: mysecretpassword
    depends_on:
      - weatherdb



#    networks:
#      - app-network


volumes:
  db_data:

#networks:
#  app-network:
#    driver: bridge